version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: lmd-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: last_mile_delivery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis lưu trữ tọa độ Real-time
  redis:
    image: redis:7-alpine
    container_name: lmd-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata: